### PR TITLE
first sheet is still visible when first sheet set hidden

### PR DESCRIPTION
**Pull request by cxn03651**
Hi,

I'm a maintainer of write_xlsx which if ruby library ported from excel-writer-xlsx.
I've fixed bug reported in https://github.com/cxn03651/write_xlsx/issues/37 .

I also wrote patch in perl, I hope this will help.

### CODE REVIEW

**Comment by jmcnamara** [comment]
Hi,

Good to talk again.

This is [documented behaviour](http://search.cpan.org/dist/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#hide()): 

> A hidden worksheet can not be activated or selected so this method is mutually exclusive with the `activate()` and `select()` methods. In addition, since the first worksheet will default to being the active worksheet, you cannot hide the first worksheet without activating another sheet:

    $worksheet2->activate();
    $worksheet1->hide();

So for example:

```perl
#!/usr/bin/perl

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook   = Excel::Writer::XLSX->new( 'hide_sheet.xlsx' );
my $worksheet1 = $workbook->add_worksheet();
my $worksheet2 = $workbook->add_worksheet();

$worksheet1->hide();
$worksheet2->activate();


$workbook->close();
```
Gives this output:

aa_image

So, I'm going to close this pull request.

Thanks,

John

**Comment by cxn03651** [comment]
thanks for your reply,

In my machine, Sheet1 is still alive.

macOS Sierra 10.12.6
perl v5.18.2
excel-writer-xlsx 0.96
Excel 2016 on Microsoft Windows 8.1


[image: 埋め込み画像 1]

2018-01-09 2:11 GMT+09:00 John McNamara <notifications@github.com>:

**Comment by cxn03651** [comment]
Hi,

I found

  $worksheet1->hide();  $worksheet2->activate();

makes good result.
However, in
http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#hide()
,

$worksheet2->activate();
$worksheet1->hide();

makes bad result I sent.

It is better to make same result independently of method sequence.

thanks,


2018-01-09 5:27 GMT+09:00 Hideo Nakamura <nakamura.hideo@gmail.com>:

**Comment by jmcnamara** [comment]
Hi,

In that case that does look like an issue.

I'll open an issue for it.

Thanks,

John

**Pull request closed without merging**
