### PR TITLE
Add combined charts in chart sheets, and "stop if true" feature to conditional formatting.

### PR DESCRIPTION
**Pull request by f20**
This patch adds support for:
* Microsoft Excel's "stop if true" feature in conditional formatting.
* Combined charts for chart sheets (rather than charts embedded on a worksheet).

### CODE REVIEW

**Comment by jmcnamara** [comment]
Hi Franck,

Thanks for the contribution.

The Contributing guide asks that all pull request start with a feature request:

https://github.com/jmcnamara/excel-writer-xlsx/blob/master/CONTRIBUTING.md

It is probably best to start there and describe what feature you would like to see added, the API, etc.

The PR isn't mergeable as it: your clone seems to be behind the master, the code formatting is different, there aren't any tests, and from a quick look it doesn't seem to be complete.

So, I would suggest starting with a feature request first and we can look at code after that.

John

**Comment by jmcnamara** [comment]
Also, I see that you have updated the PR with a fix(?) for combined charts.

PRs should patch distinct issues or features and not contain different functionality.

So, can you open an issue for that as well if it is a bug.

Thanks.

Closing this PR in the current format.

**Comment by f20** [comment]
(Subject to http://reckon.co.uk/notices/.)

Sorry, I had not realised at the time of pushing to my fork that GitHub would merge the new fix into the first pull request.

I’ll read your guidelines and reconsider!

Franck.

This message's text or attachments might be confidential or privileged.
No implied warranty of fitness for any purpose, or of any authority.
Reckon LLP, 16 Red Lion Square, London, WC1R 4QH, United Kingdom.
Limited liability partnership registered in England (number OC307897).

**Comment by jmcnamara** [comment]
The main thing is to open a feature request first.

**Pull request closed without merging**
