### PR TITLE
Icon sets

### PR DESCRIPTION
**Pull request by vlyon**
New feature: Icon sets
This has been requested in #116

I've benefited by looking at the work previously done by @Jed-Giblin in #189 but tried to adhere closely to your preferred style. I've also added documentation and a test.

### CODE REVIEW

**Comment by jmcnamara** [comment]
Thanks for the PR.

**Comment by Jed-Giblin** [comment]
@vlyon Glad my monkey patch helped out! I'll be very happy to see the feature supported by this lib

**Comment by jmcnamara** [comment]
I've pushed an implementation of conditional formatting icon support onto the https://github.com/jmcnamara/excel-writer-xlsx/tree/icon_sets branch if you want to try it out. I'll merge it to master in a few days.

**Comment by jmcnamara** [comment]
Icon sets in conditional formatting have been added in Excel::Write::Excel 0.96.

**Comment by vlyon** [comment]
@jmcnamara Thanks John. Seems fine to me.

**Pull request closed without merging**
